### ISSUE TITLE
Suckless version when?

### ISSUE THREAD

**Issue by NotElijahKing** [comfies/tldrlfs#4]
GNU coreutils are so bloated... How dare you insist that I install such garbage on my own time?! I demand that you spoonfeed me a very slightly different command.

(/s, but would be kind of cool if you did)

**Comment by kiedtl** [comment]
There's suckless sbase, which is very simple to very and very tiny. As a downside it seems to be strictly POSIX-compliant and thus doesn't contain many features present in the GNU coreutils.

Then there's busybox ;)

**Comment by Sweets** [comment]
i got you fam
